CA1/CA1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CA1.Models;
using CA1.DAL;

namespace CA1.Controllers
{
    public class HomeController : Controller
    {
        private tourContext db = new tourContext();

        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View(db.Trip.ToList());
        }

        //
        // GET: /Home/Details/5

        public ActionResult Details(int id = 0)
        {
            Trip trip = db.Trip.Find(id);
            if (trip == null)
            {
                return HttpNotFound();
            }
            return View(trip);
        }

        //
        // GET: /Home/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Home/Create

        [HttpPost]
        public ActionResult Create(Trip trip)
        {
            if (ModelState.IsValid)
            {
                db.Trip.Add(trip);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(trip);
        }

        public ActionResult CreateLeg()
        {
            return View();
        }

        //
        // POST: /Home/Create

        [HttpPost]
        public ActionResult CreateLeg(Legs legs)
        {
            if (ModelState.IsValid)
            {
                db.Legs.Add(legs);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(legs);
        }

        //
        // GET: /Home/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Trip trip = db.Trip.Find(id);
            if (trip == null)
            {
                return HttpNotFound();
            }
            return View(trip);
        }

        //
        // POST: /Home/Edit/5

        [HttpPost]
        public ActionResult Edit(Trip trip)
        {
            if (ModelState.IsValid)
            {
                db.Entry(trip).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(trip);
        }

        //
        // GET: /Home/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Trip trip = db.Trip.Find(id);
            if (trip == null)
            {
                return HttpNotFound();
            }
            return View(trip);
        }

        //
        // POST: /Home/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Trip trip = db.Trip.Find(id);
            db.Trip.Remove(trip);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

CA1/CA1/Controllers/LegsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CA1.Models;
using CA1.DAL;

namespace CA1.Controllers
{
    public class LegsController : Controller
    {
        private tourContext db = new tourContext();

        //
        // GET: /Legs/

        public ActionResult Index()
        {
            return View(db.Legs.ToList());
        }

        //
        // GET: /Legs/Details/5

        public ActionResult Details(int id = 0)
        {
            Legs legs = db.Legs.Find(id);
            if (legs == null)
            {
                return HttpNotFound();
            }
            return View(legs);
        }

        //
        // GET: /Legs/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Legs/Create

        [HttpPost]
        public ActionResult Create(Legs legs)
        {
            if (ModelState.IsValid)
            {
                db.Legs.Add(legs);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(legs);
        }

        //
        // GET: /Legs/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Legs legs = db.Legs.Find(id);
            if (legs == null)
            {
                return HttpNotFound();
            }
            return View(legs);
        }

        //
        // POST: /Legs/Edit/5

        [HttpPost]
        public ActionResult Edit(Legs legs)
        {
            if (ModelState.IsValid)
            {
                db.Entry(legs).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(legs);
        }

        //
        // GET: /Legs/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Legs legs = db.Legs.Find(id);
            if (legs == null)
            {
                return HttpNotFound();
            }
            return View(legs);
        }

        //
        // POST: /Legs/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Legs legs = db.Legs.Find(id);
            db.Legs.Remove(legs);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

CA1/CA1/Views/Home/Create.cshtml
@model CA1.Models.Trip

@{
    ViewBag.Title = "Create";
}

<h2 style="margin-left:12.5%; color:#042df2">Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset style="margin-left:12.5%; color:#042df2">
        <legend style="color:#042df2">Trip</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.name)
            @Html.ValidationMessageFor(model => model.name)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.startDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.startDate)
            @Html.ValidationMessageFor(model => model.startDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.endDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.endDate)
            @Html.ValidationMessageFor(model => model.endDate)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div style="margin-left:12.5%; color:#042df2">
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CA1/CA1/Views/Home/CreateLeg.cshtml
@model CA1.Models.Legs

@{
    ViewBag.Title = "CreateLeg";
}

<h2 style="margin-left:12.5%; color:#042df2">Create Leg</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset style="margin-left:12.5%; color:#042df2">
        <legend style="color:#042df2">Legs</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.startLocal)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.startLocal)
            @Html.ValidationMessageFor(model => model.startLocal)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.finishLocal)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.finishLocal)
            @Html.ValidationMessageFor(model => model.finishLocal)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.startDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.startDate)
            @Html.ValidationMessageFor(model => model.startDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.endDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.endDate)
            @Html.ValidationMessageFor(model => model.endDate)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div style="margin-left:12.5%">
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CA1/CA1/Views/Home/Delete.cshtml
@model CA1.Models.Trip

@{
    ViewBag.Title = "Delete";
}

<h2 style="margin-left:12.5%; color:#042df2">Delete</h2>

<h3 style="margin-left:12.5%; color:#042df2">Are you sure you want to delete this?</h3>
<fieldset style="margin-left:12.5%; color:#042df2">
    <legend style="color:#042df2">Trip</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.startDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.startDate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.endDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.endDate)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p style="margin-left:12.5%; color:#042df2">
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

CA1/CA1/Views/Home/Details.cshtml
@model CA1.Models.Trip

@{
    ViewBag.Title = "Details";
}

<h2 style="margin-left:12.5%; color:#042df2">Details</h2>

<fieldset style="margin-left:12.5%; color:#042df2">
    <legend style="color:#042df2">Trip</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.startDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.startDate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.endDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.endDate)
    </div>
</fieldset>
<p style="margin-left:12.5%; color:#042df2">
    @Html.ActionLink("Edit", "Edit", new { id=Model.tripID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CA1/CA1/Views/Home/Edit.cshtml
@model CA1.Models.Trip

@{
    ViewBag.Title = "Edit";
}

<h2 style="margin-left:12.5%; color:#042df2">Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset style="margin-left:12.5%; color:#042df2">
        <legend style="color:#042df2">Trip</legend>

        @Html.HiddenFor(model => model.tripID)

        <div class="editor-label">
            @Html.LabelFor(model => model.name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.name)
            @Html.ValidationMessageFor(model => model.name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.startDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.startDate)
            @Html.ValidationMessageFor(model => model.startDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.endDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.endDate)
            @Html.ValidationMessageFor(model => model.endDate)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div style="margin-left:12.5%; color:#042df2">
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CA1/CA1/Views/Home/Index.cshtml
@model IEnumerable<CA1.Models.Trip>

@{
    ViewBag.Title = "Index";
}

<h2></h2>

<p style="margin-left:12.5%">
    @Html.ActionLink("Create New", "Create")
</p>
<p style="margin-left:12.5%">
    @Html.ActionLink("Add Leg", "CreateLeg")
</p>
<p style="margin-left:12.5%">
    @Html.ActionLink("Show Legs","Index","Legs")
</p>
<table style="color:#042df2; margin-left:12.5%; border-radius:6px">
    <tr>
        <th style="width:20%">
            @Html.DisplayNameFor(model => model.name)
            @*@Html.DisplayFor()*@
        </th>
        <th >
            @Html.DisplayNameFor(model => model.startDate)
        </th>
        <th style="width:20%">
            @Html.DisplayNameFor(model => model.endDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Viable)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NotViable)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.startDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.endDate)
        </td>
         <td>
            @Html.DisplayFor(modelItem => item.Viable)
        </td>
         <td>
            @Html.DisplayFor(modelItem => item.NotViable)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.tripID }) |
            @Html.ActionLink("Details", "Details", new { id=item.tripID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.tripID })
        </td>
    </tr>
}
    
</table>